apiVersion: v1
kind: Pod 
metadata: 
  name: probe-pod
spec:
  containers:
  - name: curl
    image: rancher/curl
    command: ["/bin/sh"]
    args: ["-c","while true; do curl details:9080; sleep 1; done"]