version: '3.3'

services:
  productpage:
    build:
      context: .
      dockerfile: ProductPage_Dockerfile
    image: equipo9/productpage
    # volumes:
    #   - productpage:/home/node/app
    restart: always
    ports:
      - 9080:9080
    links:
      - "details"

  details:
    build:
      context: .
      dockerfile: Details_Dockerfile
    image: equipo9/details
    restart: always
    expose:
      - 9080

  reviews:
    build:
      context: app/bookinfo/src/reviews/reviews-wlpcfg
      dockerfile: Dockerfile
      args:
        service_version: v1
        enable_ratings: "true"
        star_color: "black"
    image: equipo9/reviews
    restart: always
    expose:
      - 9080

  ratings:
    build:
      context: .
      dockerfile: Ratings_Dockerfile
    image: equipo9/ratings
    restart: always
    expose:
      - 9080