apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  labels:
    app: ratings
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
      - name: equipo9-k8s-ratings
        image: arcones/equipo9-k8s-ratings
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080